name: Linux CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-18.04
    
    steps:
    - uses: actions/checkout@v2
    - name: Compile vcpkg dependencies
      run: ./vcpkg_linux.sh
    - name: Compile Duke3D
      run: ./build_linux.sh
